### ISSUE TITLE
读取csv文件的问题

### ISSUE THREAD

**Issue by th0o0** [duxuhao/JData-2018#1]
`basic_info = pd.read_csv('B/jdata_user_basic_info.csv')`是不是应该
`basic_info = pd.read_csv('../B/jdata_user_basic_info.csv')`

**Comment by duxuhao** [comment]
你好，因为我是直接执行Feature_Engineering.sh的文件的，所以我写的是B/jdata_user_basic_info.csv，如果你是需要单个执行的话，确实需要做对应的修改。

**Comment by th0o0** [comment]
OK
